printf "Hello Drew. Welcome to your Mac. "
alias gist="cd ~/gist"
alias stagec="ssh root@172.27.70.41"
alias corpus="cd /Users/Drew/Documents/GISC\ Project/cigsdev_corpus_v1/; sudo npm start;"
alias mvp="cd /Users/Drew/Documents/GISC\ Project/cigsdev_mvp_v1/; sudo npm start;" 
